---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - php
  fixme:
    enabled: true
  phpmd:
    enabled: true
    checks:
      Controversial/CamelCaseParameterName:
        enabled: false
      Controversial/CamelCasePropertyName:
        enabled: false
      Controversial/CamelCaseVariableName:
        enabled: false
      Naming/LongVariable:
        enabled: false
      Naming/ShortVariable:
        enabled: false
ratings:
  paths:
  - "**.js"
  - "**.php"
exclude_paths: []
