name: GrumPHP
on: push

jobs:
  grumphp:
    runs-on: ubuntu-latest
    container: docker://php:${{ matrix.php_version }}-cli
    continue-on-error: ${{ matrix.allow_fail }}
    strategy:
      matrix:
        php_version:
        - '7.1'
        - '7.2'
        - '7.3'
        - '7.4'
        allow_fail: [false]
        include:
          - php_version: 8.0-rc
            allow_fail: true
    steps:
      - uses: actions/checkout@v2
      - name: Install Extensions
        run: |
          pecl install pcntl
          pecl install posix
      - name: Install Composer
        run: |
          php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
          php -r "if (hash_file('sha384', 'composer-setup.php') === 'e5325b19b381bfd88ce90a5ddb7823406b2a38cff6bb704b0acc289a09c8128d4a8ce2bbafcd1fcbdc38666422fe2806') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
          php composer-setup.php
          php -r "unlink('composer-setup.php');"
      - name: Composer install
        run: php composer.phar install
      - name: GrumPHP
        run: |
          vendor/bin/grumphp run
